### ISSUE TITLE
🐛 [Bug]: Error when executing 'tiny init'

### ISSUE THREAD

**Issue by howling-wind** [opentiny/tiny-cli#1]
### Version

v1.0.0-alpha.0

### Link to minimal reproduction

Not involved in

### Step to reproduce

1. npm i @opentiny/cli npminstall -g
2. tiny -v
tiny v1.0.0-alpha.0
3. tiny init

### What is actually happening

![image](https://user-images.githubusercontent.com/119645349/207800135-26e33a18-f213-4d6e-b95f-a07d238458c4.png)

**Comment by hello-yezi** [comment]
I'm sorry for replying so late. The problem has been resolved and you can try using it again.
[Functional verification]
![image](https://user-images.githubusercontent.com/75346211/229705285-4e1c2ce3-0c67-4c01-b310-06febddbbca1.png)

**Comment by hello-yezi** [comment]
This issue is closed at this time. If you have any questions, please contact us again.
