### ISSUE TITLE
🐛 [Bug]: TinyPro 项目在移动端显示错位

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#10]
### Version

latest

### node-version

latest

### Link to minimal reproduction

手机浏览器访问以下页面错位：

https://opentiny.design/vue-pro/pages

<img width="356" alt="image" src="https://user-images.githubusercontent.com/9566362/230721105-37aa653c-5344-499a-a4e4-e3c59a0f9c8b.png">

### Step to reproduce

手机浏览器访问以下页面错位：

https://opentiny.design/vue-pro/pages

<img width="356" alt="image" src="https://user-images.githubusercontent.com/9566362/230721105-37aa653c-5344-499a-a4e4-e3c59a0f9c8b.png">

**Comment by aliceDxr** [comment]
tinyPro作为一款PC中后台工具，暂时是没有兼容移动端使用的，后续我们会持续优化

**Comment by h-ivy** [comment]
不支持移动端
