### ISSUE TITLE
🐛 [Bug]: linux系统执行tiny init 报错

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-cli#107]
### Version

latest

### node-version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-cli/assets/48880836/bebf55d9-726b-4adc-be29-6ecf074b9554)

### Step to reproduce

![image](https://github.com/opentiny/tiny-cli/assets/48880836/6f00077e-7332-43be-9783-732539c8acec)

**Comment by fengyon** [comment]
感谢您的反馈，我们将尽快排查原因并修复此问题

**Comment by fengyon** [comment]
感谢您的反馈，经过团队讨论，目前TinyCli不支持 linux运行，短期内暂时没有支持 linux的计划

如果您非常期望TinyCli支持linux，可以重开此issue重新进行讨论，也欢迎您提交PR
