### ISSUE TITLE
✨ [Feature]: 希望tinypro增加tab多页签显示

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-cli#108]
### What problem does this feature solve

现在只有单页面显示,切换页面时只能显示当前页面。

### What does the proposed API look like

希望增加 tab 切换显示页面， 并可针对不同的页面设置是否要keep-alive 。

**Comment by fengyon** [comment]
感谢您提出的建议，此建议非常有用，可以极大地丰富开发场景
但是由于排期原因，短期内没有开发此功能的计划

您可以参考[tinyvue tab组件的文档](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs)自行开发此功能，也欢迎提交PR贡献

最后，我们将暂时关闭此issue，将来有计划时再重开此issue。
如有需求，您也可以重开此issue，我们将重新讨论此功能的计划。
