### ISSUE TITLE
🐛 [Bug]: tinyPro Vue 菜单样式错乱

### ISSUE THREAD

**Issue by liberty-zlk** [opentiny/tiny-cli#113]
### Version

latest

### node-version

latest

### Step to reproduce

@opentiny/vue升级到最新版本3.11.0版本之后，菜单样式错乱
![image](https://github.com/opentiny/tiny-cli/assets/106023244/bca9c4ca-ecba-46a9-8323-5e1dd5d029c8)

### What is expected

No response

### What is actually happening

No response

### Any additional comments (optional)

No response

**Comment by liberty-zlk** [comment]
已修复
![image](https://github.com/opentiny/tiny-cli/assets/106023244/1f64d9c8-f777-47ed-9a71-ab805103de0e)

**Comment by fengyon** [comment]
the issue has been fixed by #114 , so closed it
