### ISSUE TITLE
🐛 [Bug]: scrolling performance issue on overview page

### ISSUE THREAD

**Issue by speedmax123** [opentiny/tiny-cli#12]
### Version

latest

### node-version

latest

### Link to minimal reproduction

open https://opentiny.design/tiny-ng/overview
open chrome dev tools, select rendering, select ```Pain flashing```
![image](https://user-images.githubusercontent.com/3250500/230764462-e3791505-3684-4eca-8b18-bbcdcf5b9752.png)
Then scroll the doc, as you can see all items on the page was repainted.

### Step to reproduce

open https://opentiny.design/tiny-ng/overview
open chrome dev tools, select rendering, select ```Pain flashing```
![image](https://user-images.githubusercontent.com/3250500/230764462-e3791505-3684-4eca-8b18-bbcdcf5b9752.png)
Then scroll the doc, as you can see all items on the page was repainted.

### What is expected

Since the overview page is pretty simple from functional perspective, page FPS should keep as high as your monitor 60/90/144.

### What is actually happening

But in fact, it has dropped ~20 FPS in each scroll. if you click the ```Frame rendering stats``` as well on the rendering tab of chrome dev tools. And you can see everything inside the ```.n-layout-scroll-container``` was repaint due to each scrolling.

No scrolling (~141 fps)
![image](https://user-images.githubusercontent.com/3250500/230764699-ccaa2d1b-65df-4c5e-b380-f66087ed2e74.png)
Scrolling  (~126 fps)
![image](https://user-images.githubusercontent.com/3250500/230764742-c6a9fc11-6369-4fa5-9e0e-e8dbf4aaa6a8.png)

I suggest add css
```
will-change: transform;
```
in ```.n-layout-scroll-container```

### Any additional comments (optional)

I use a game monitor as default fresh rate is 144 hz.
So when people are using high fresh rate screen like game monitor or premium phone, they would be much easier to detect the scrolling performance issue of the page.
Pretty sure we should take care of the use cases like this in documentation web site. For details you can see
https://dev.opera.com/articles/css-will-change-property/
If you do not tell chrome to render the element using GPU then it will have a long repaint phase in the middle.

**Comment by fengyon** [comment]
Thank you very much for your feedback. This problem is very important and we are trying to fix it.

**Comment by aliceDxr** [comment]
thx for advise  ~  we have fixed it~
