### ISSUE TITLE
🐛 [Bug]: mock false 无效 并不能启用非mock 模式

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#124]
### Version

latest

### node-version

latest

### Link to minimal reproduction

Refer to https://github.com/opentiny/tiny-cli/issues/125

### Step to reproduce

Refer to https://github.com/opentiny/tiny-cli/issues/125

**Comment by fengyon** [comment]
This issue is repeated with anthor issue that was transfered from tinyvue, so closed it

the transfered issue:
https://github.com/opentiny/tiny-cli/issues/125
