### ISSUE TITLE
🐛 [Bug]:keep-alive时不起作用，无法实现路由缓存

### ISSUE THREAD

**Issue by Real047** [opentiny/tiny-cli#126]
### Version

tiny v1.1.0

### node-version

v16.20.2

### Step to reproduce

为了实现Tabs切换功能，我要用到路由缓存keep-alive，但一直不起作用，试了很多种方法还是一样，然后新建项目试了一下还是keepalive不生效，没法实现路由缓存。

**Comment by fengyon** [comment]
感谢您的反馈，请提供一下复现demo，以便更快地排查此问题

**Comment by Real047** [comment]
好的，下面提供了页面的源代码和效果，要达到的目的

**router-view和keep-alive使用的页面**
![image](https://github.com/opentiny/tiny-cli/assets/148325129/b4491fe5-84c2-4a5b-b0aa-ce74e030b3cd)
页面A
![image](https://github.com/opentiny/tiny-cli/assets/148325129/9ab365a1-7d1f-4f7e-8c5a-5055ca91486d)
页面B
![image](https://github.com/opentiny/tiny-cli/assets/148325129/d9d56783-e55d-4290-9e88-f0e07f50eb82)

**效果**
页面A
![image](https://github.com/opentiny/tiny-cli/assets/148325129/44d0cd96-ece1-421b-9fd4-2be02f0a5745)
页面B
![image](https://github.com/opentiny/tiny-cli/assets/148325129/50729dfe-4c11-492a-adbb-bac20237e6b1)
**目的**
我需要实现切换路由时缓存各页面的input保留输入的数据，不重新加载页面，不重新发送请求（不仅是input）

**Comment by Real047** [comment]
demo 源代码
[keep_alive.zip](https://github.com/opentiny/tiny-cli/files/13841051/keep_alive.zip)

**Comment by h-ivy** [comment]
你试一下这样改吧
<template>
  <div class="tabs">
    <tiny-radio-group v-model="activeName" @change="onChange">
      <tiny-radio-button label="A">页面A</tiny-radio-button>
      <tiny-radio-button label="B">页面B</tiny-radio-button>
    </tiny-radio-group>
    <span> {{ new Date().toTimeString() }}</span>
  </div>
    <keep-alive>
      <component :is="curr.value" />
    </keep-alive>
</template>

<script lang="ts" setup>
import { ref ,reactive ,markRaw} from 'vue'
import { RadioGroup as TinyRadioGroup, RadioButton as TinyRadioButton } from '@opentiny/vue'
import AVue from "./A/index.vue"
import BVue from "./B/index.vue"

// 方案一： 无路由， 仅在页面级进行组件切换，验证缓存： 【验证成功】
const activeName = ref('A')
const curr= reactive({
  value: markRaw(AVue)
})
const onChange = (event: any) => {
  if(event==='A'){
    curr.value=markRaw(AVue)
  }else{
    curr.value=markRaw(BVue)
  }

}
</script>

<style scoped lang="less">
.tabs {
  margin-top: 10px;
  width: 100%;
  height: 60px;
  background-color: white;
}
</style>

**Comment by h-ivy** [comment]
<template>
  <div class="tabs">
    <tiny-radio-group v-model="activeName" @change="onChange">
      <tiny-radio-button label="A">页面A</tiny-radio-button>
      <tiny-radio-button label="B">页面B</tiny-radio-button>
    </tiny-radio-group>
    <span> {{ new Date().toTimeString() }}</span>
  </div>
    <keep-alive>
      <component :is="curr.value" />
    </keep-alive>
</template>

<script lang="ts" setup>
import { ref ,reactive ,markRaw} from 'vue'
import { RadioGroup as TinyRadioGroup, RadioButton as TinyRadioButton } from '@opentiny/vue'
import AVue from "./A/index.vue"
import BVue from "./B/index.vue"

// 方案一： 无路由， 仅在页面级进行组件切换，验证缓存： 【验证成功】
const activeName = ref('A')
const curr= reactive({
  value: markRaw(AVue)
})
const onChange = (event: any) => {
  if(event==='A'){
    curr.value=markRaw(AVue)
  }else{
    curr.value=markRaw(BVue)
  }

}
</script>

<style scoped lang="less">
.tabs {
  margin-top: 10px;
  width: 100%;
  height: 60px;
  background-color: white;
}
</style>

**Comment by h-ivy** [comment]
![Uploading 截图.PNG…]()

**Comment by shenjunjian** [comment]
经过分析，原因是**因为 keep/index.vue 这一层组件在切换路由时， 整体切换了，所以它里面的keep-alive也不会有效果**。
证明图：
![image](https://github.com/opentiny/tiny-cli/assets/6848520/f43644f4-35d9-40da-b08d-58003a322639)

**Comment by shenjunjian** [comment]
【方案一】不依赖路由， 仅在页面级进行组件切换，验证缓存
将A,B直接引入 index.vue
index.vue的模板改为：
```html
    <keep-alive>
      <component :is="curr.value" />
    </keep-alive>
``` 

脚本：
```javascript
import { ref ,reactive ,markRaw} from 'vue'
import { RadioGroup as TinyRadioGroup, RadioButton as TinyRadioButton } from '@opentiny/vue'
import AVue from "./A/index.vue"
import BVue from "./B/index.vue"

const activeName = ref('A')
const curr= reactive({
  value: markRaw(AVue)
})
const onChange = (event: any) => {
  if(event==='A'){
    curr.value=markRaw(AVue)
  }else{
    curr.value=markRaw(BVue)
  }
}
```

**Comment by shenjunjian** [comment]
【方案2】 使用路由缓存， 但是路由的keey-alive要在上级路由中添加
打开 src/layout/page-layout.vue 添加：
```html
  <router-view v-slot="{ Component, route }">
    <keep-alive>
    <component :is="Component" :key="route.fullPath" />
  </keep-alive>
  </router-view>
```

然后index.vue不需要变化。

结论： 想缓存keep中的路由页面，必须在keep的父级的router-view进行缓存。
