### ISSUE TITLE
🐛 [Bug]: pro示例套件菜单点击报Maximum call stack size exceeded，页面无法跳转

### ISSUE THREAD

**Issue by qichaoh** [opentiny/tiny-cli#128]
### Version

v1.1.0

### node-version

v16.14.2

### Link to minimal reproduction

按照文档tiny-cli的方法创建新项目，选pro + vue. 

### Step to reproduce

tiny-cli新创建的项目，随机点几个菜单之后点击个人中心，或者直接点个人中心菜单，基本属于必现。
![image](https://github.com/opentiny/tiny-cli/assets/43289749/34860543-f16d-4fc7-9323-c9a328b7c1f8)

### What is expected

不报错，页面正常跳转

### What is actually happening

报错RangeError: Maximum call stack size exceeded at triggerEffects，路由无法跳转，点击其他菜单路由也无法跳转

**Comment by fengyon** [comment]
感谢您的反馈，我们已经排查出问题并将尽快发版修复
修复措施：
1、文件: src/store/modules/app/index.ts 第 10 行
```
 - return { ...state };
 + return state;
```
2、文件: src/store/modules/user/index.ts 第40行
```
 - return { ...state };
 + return state;
```
