### ISSUE TITLE
✨ [Feature]: 能否在TinyPro增加一下权限管控案例

### ISSUE THREAD

**Issue by wanghepeng1986** [opentiny/tiny-cli#135]
### What problem does this feature solve

比如：菜单权限管控，用户权限管控、列和按钮权限管控.
这样可以实现网站后台管理系统操作

### What does the proposed API look like

[](url)
![01](https://github.com/opentiny/tiny-cli/assets/34325561/a8e492d6-f060-4dc9-846c-dbb2d857f974)
![02](https://github.com/opentiny/tiny-cli/assets/34325561/6720e7aa-9d74-4e91-95a9-3bf23de644c1)
![03](https://github.com/opentiny/tiny-cli/assets/34325561/ae52e612-a488-4241-96db-4000a8ae355e)

**Comment by GaoNeng-wWw** [comment]
#149 #159 #139
