### ISSUE TITLE
🐛 [Bug]: Tiny pro Vue 不使用mock数据登录请求异常

### ISSUE THREAD

**Issue by onemiless** [opentiny/tiny-cli#14]
### Version

tiny v1.0.0-alpha.3

### node-version

v16.18.0

### Step to reproduce

关闭mock后，使用后端api，点击登录时axios 请求出错
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/44081883/231089053-07e13b68-c3ff-49d5-bd81-1ea0febba8cf.png">

**Comment by fengyon** [comment]
可以看一下你的api/interceptor.ts文件吗？
如果是是使用项目模板的`api/interceptor.ts`文件，这个文件只是提供一个模板，设定的响应拦截规则是 响应码不是 20000就返回错误的promise，报错可能是正常的。
因此关闭mock后需要根据后端API的逻辑修改 `api/interceptor.ts` 文件。

![Untitled](https://user-images.githubusercontent.com/84690330/231387647-dac18f62-992b-42ac-9bf0-52dfc8ff451f.png)

**Comment by fengyon** [comment]
已经长时间没有新的回复，默认已经解决，因此关闭此issue。
如果未解决，重新开启issue即可。
