### ISSUE TITLE
[官网] uc浏览器不显示顶部导航，左侧菜单无法关闭

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#16]
uc浏览器不显示顶部导航，左侧菜单无法关闭。

![Screenshot_20230412_111004_com.UCMobile.jpg](https://user-images.githubusercontent.com/9566362/231338875-4ac57350-9ab0-4de3-88a9-ee97ecf0239d.jpg)

**Comment by aliceDxr** [comment]
正在跟进 ~

**Comment by aliceDxr** [comment]
升级到新版本的UC浏览器是正常显示的
