### ISSUE TITLE
🐛 [Bug]: 使用官方教程tinycli创建的tiny-pro-vue默认为vue3的版本，希望未来能支持选择生成vue2的版本

### ISSUE THREAD

**Issue by lipan007** [opentiny/tiny-cli#22]
### Version

tiny v1.0.1 @opentiny/tiny-toolkit-vue-pro v1.0.0-alpha.5

### node-version

v16.14.2

### Step to reproduce

1、安装脚手架npm install @opentiny/cli npminstall@3 -g
2、tiny init 选择 vue-pro
3、tiny start ，查看vue版本为3.2.31，目前使用vue2较多，希望后续可以支持

**Comment by fengyon** [comment]
已将vue2的初始化加入规划，预计2个月内启动开发

**Comment by lipan007** [comment]
感谢感谢
