### ISSUE TITLE
✨ [Feature]: Axios配置添加错误状态码的配置

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-cli#223]
### What problem does this feature solve

用户更好的使用错误状态码路由拦截这一块的样式，真正做到“开箱即用”

### What does the proposed API look like

axios的请求状态码错误或者报错了，弹出一些已经配置好的错误提示，不用用户在自己额外书写
<img width="556" alt="image" src="https://github.com/user-attachments/assets/13b9db60-4fa2-4498-b18a-72e78165ce64">

**Comment by GaoNeng-wWw** [comment]
错误提示更推荐在后端进行操作，因为报错行为本身是后端发起的。后端只需要拿到请求头, 根据请求头来判断返回的国际化词条即可

#197
