### ISSUE TITLE
🐛 [Bug]: 官网滚动条出现横向滚动条和双滚动条的样式问题

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#37]
### Version

latest

### node-version

latest

### Step to reproduce

Chrome 浏览器版本
![image](https://github.com/opentiny/tiny-cli/assets/9566362/e9b608b5-bebe-40eb-aa14-c4e0c038c7dc)

以下链接滚动条样式有双滚动条和横向滚动条问题

横向滚动条问题：
[https://opentiny.design/](https://opentiny.design/)

![image](https://github.com/opentiny/tiny-cli/assets/9566362/e3892497-d620-4bda-bd04-ac37d05bc789)

双滚动条问题：
[https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/envpreparation](https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/envpreparation)

![image](https://github.com/opentiny/tiny-cli/assets/9566362/205aff6f-79a6-4754-838f-e3091fc2e6d2)

建议解决方案：
移除body元素中的`overflow: auto`

![image](https://github.com/opentiny/tiny-cli/assets/9566362/affb005b-3be6-44cd-9504-9388d6483aea)

![image](https://github.com/opentiny/tiny-cli/assets/9566362/ccc44fc3-7b04-4307-818b-3d9380674a3c)

**Comment by aliceDxr** [comment]
已解决~
