### ISSUE TITLE
🐛 [Bug]: tiny init ng-pro安装的最新版本，tiny start启动时报错，貌似发的包有问题

### ISSUE THREAD

**Issue by zhaoweikai** [opentiny/tiny-cli#4]
### Version

默认版本

### Link to minimal reproduction

![image](https://user-images.githubusercontent.com/10459842/211181558-6508bb4d-8cf3-40d1-95d9-56a280e6268a.png)

### Step to reproduce

看标题。

**Comment by hello-yezi** [comment]
I'm sorry for replying so late. The problem has been resolved and you can try using it again.
![image](https://user-images.githubusercontent.com/75346211/229709224-ac9e681e-a98c-4bc8-9bda-4c5ed75ec27a.png)

**Comment by hello-yezi** [comment]
This issue is closed at this time. If you have any questions, please contact us again.
