### ISSUE TITLE
🐛 [Bug]: TinyPro of Vue 的页面文字颜色有点奇怪

### ISSUE THREAD

**Issue by vaebe** [opentiny/tiny-cli#51]
### Version

latest

### node-version

latest

### Link to minimal reproduction

https://opentiny.design/vue-pro/docs/start
<img width="1061" alt="截屏2023-06-01 下午10 36 25" src="https://github.com/opentiny/tiny-cli/assets/52314078/76e7828b-afac-4e06-83c2-245ddcff91a3">

### Step to reproduce

打开 https://opentiny.design/vue-pro/docs/start 链接即可

### What is expected

<img width="1054" alt="截屏2023-06-01 下午10 37 11" src="https://github.com/opentiny/tiny-cli/assets/52314078/03e51852-4f5d-4e39-8992-d71ce0ec8a9d">

### What is actually happening

TinyPro of Vue 的页面文字颜色有点看不清

**Comment by kagol** [comment]
@vaebe 感谢vaebe同学的反馈，我们尽快看下~

**Comment by h-ivy** [comment]
@vaebe ,是什么浏览器发现的，我本地显示是好的，谢谢

**Comment by vaebe** [comment]
> @vaebe ,是什么浏览器发现的，我本地显示是好的，谢谢

现在显示确实是正常的！ @h-ivy

**Comment by h-ivy** [comment]
@vaebe ，ok，有问题再联系我，谢谢！
