### ISSUE TITLE
✨ [Feature]: 关于 tiny init 项目的改进意见

### ISSUE THREAD

**Issue by robinv8** [opentiny/tiny-cli#53]
### What problem does this feature solve

当前创建项目方式：
```bash
tiny init [toolkitName] 
```
其中 toolkitName 为套件名，不太符合当下 init 项目的命令行规范，建议 init 后面跟项目名，如：
```bash
tiny init [projectName] 
```
然后在 cli 里面支持选择套件的功能

### What does the proposed API look like

tiny init [projectName]

**Comment by h-ivy** [comment]
@robinv8 ,谢谢您的反馈。一般都要先选择了某个套件之后，进入套件之后，会让你输入projectName。当然先输入projectName，再选择套件，也是一种交互模式，只要整个cli统一就行，另外输入tiny init命令，能查看所有的套件列表，再次感谢您的反馈。

**Comment by kagol** [comment]
@h-ivy 还有有一个问题，现在我们的 tiny init [toolkitName] 有一个问题，就是会直接在当前目录下面生成文件，即使我输入了项目名称也一样，这和业界的cli命令行工具不一致，而且如果用户没有提前创建一个文件夹，就会导致创建出来的项目文件都铺开在了当前目录，不是很友好，建议优化下



tiny init vue-pro

执行完，输入项目名称 my-tiny-pro

预期：

应该在当前目录创建一个文件夹，叫：my-tiny-pro，然后将项目的文件/文件夹都放在这个文件夹下面

实际：

项目文件/文件夹都铺开在当前目录，并没有用一个文件夹包裹起来
