### ISSUE TITLE
✨ [Feature]: 初始化创建工程时，最小化打印信息，比如：默认不打印文件创建日志信息

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#54]
### What problem does this feature solve

提升开发体验

### What does the proposed API look like

若添加 `verbose` 参数，才打印全量信息。

**Comment by aliceDxr** [comment]
是哪个工程呢 ~

**Comment by kagol** [comment]
> 是哪个工程呢 ~

@aliceDxr 使用以下命令：tiny init vue-pro 创建初始化工程时，默认会打印大量的创建文件的日志，其他命令也可以排查下是否有同样的问题

**Comment by h-ivy** [comment]
tiny init vue-pro命令已经废弃，请使用新命令tiny init pro
