### ISSUE TITLE
🐛 [Bug]: 使用 tiny init 创建的 vue-pro 项目缺失 .gitignore 文件

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#6]
### Version

v1.0.0-alpha.3

### node-version

v16.18.0

### Link to minimal reproduction

复现步骤：
- 安装 tiny
- 执行 tiny init 命令，选择 vue-pro

根目录下没有 `.gitignore` 文件，会导致开发者使用 `git add .` / `git commit -m "init project"`时，会误将 `node_modules` 目录提交到 Git 仓库中。

```
$ tiny -v
tiny v1.0.0-alpha.3
@opentiny/tiny-toolkit-vue-pro v1.0.0-alpha.5
```

### Step to reproduce

复现步骤：
- 安装 tiny
- 执行 tiny init 命令，选择 vue-pro

### What is expected

根目录包含 `.gitignore` 文件

### What is actually happening

根目录未包含 `.gitignore` 文件

**Comment by fengyon** [comment]
此问题已经解决，使用最新的pro套件初始化项目即可
```
tiny init pro
```

```
 ? 请输入项目名称： 
 ? 请输入项目描述： (基于TinyPro套件创建的中后台系统)
 ? 请选择你希望使用的技术栈： (Use arrow keys)
 > vue
   angular
```
