### ISSUE TITLE
🐛 [Bug]: 主题配置系统的消息提示和整体风格不搭

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#61]
### Version

latest

### node-version

latest

### Link to minimal reproduction

创建完一个主题之后，弹出来的消息提示，样式和整体网站风格不搭，建议优化为使用OpenTiny组件

![主题配置提示框](https://github.com/opentiny/tiny-cli/assets/9566362/921ba1ca-b8c6-4b8c-ba1d-3c53ccb361fb)

### Step to reproduce

如上

**Comment by h-ivy** [comment]
已转同事处理
