### ISSUE TITLE
🐛 [Bug]: tiny init vue-pro生成的项目建议增加 .gitignore 文件

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#62]
### Version

latest

### node-version

latest

### Step to reproduce

目前用  tiny init vue-pro 生成的项目，没有 .gitignore 文件，用 git 提交之后会把 node_modules 也提交到git仓库，不太合理

**Comment by h-ivy** [comment]
@kagol tiny init vue-pro已经废弃了，请使用tiny init pro命令，确认了，tiny init pro命令初始化出来的工程已包含.gitignore文件
