### ISSUE TITLE
🐛 [Bug]: tiny init pro 命令创建的项目，本地启动之后无法登录

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#66]
### Version

latest

### node-version

latest

### Step to reproduce

复现步骤：
1. 使用 tiny init pro 命令创建一个 vue-pro 项目
2. 进入 web 目录，执行 tiny start
3. 浏览器访问 http://localhost:3031/
4. 点击登录按钮一直转圈，没法登录

命令行控制台提示以下错误：
```
23:54:11 [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:7001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

怀疑是依赖后端服务，于是尝试以下解决方案：
1. 进入 server 目录，执行 npm i
2. 执行 npm run dev ，报错：`2023-06-26 23:54:54,128 ERROR 40990 nodejs.SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306`

无果。

**Comment by wjiangwang** [comment]
数据库未初始化导致的报错。
已新增选择对接后台会自动创建数据库和数据表（需提前要安装mysql）
相关文档readme也已更新 https://www.opentiny.design/tiny-cli/docs/toolkits/pro
