### ISSUE TITLE
🐛 [Bug]: 在执行"tiny init pro"时 ,选择服务器技术栈"Spring Cloud", 会报"项目模板创建失败"

### ISSUE THREAD

**Issue by heise100** [opentiny/tiny-cli#72]
### Version

tiny v1.0.1

### node-version

v18.16.1

### Step to reproduce

![8bb3197b05357445f1af2f4d6a06eba](https://github.com/opentiny/tiny-cli/assets/3273010/942a179b-9d47-4140-8c69-483c4e4a7ed3)
![image](https://github.com/opentiny/tiny-cli/assets/3273010/f8692eb2-dd31-4661-bbad-746a9336ba6f)

### What is expected

建议参考若依开发平台, 部署过程清晰
https://doc.ruoyi.vip/ruoyi-vue/document/hjbs.html#准备工作
后端可以不以增加SpringBoot版本

**Comment by wjiangwang** [comment]
非常感谢您的反馈，意见已经收到。Spring Cloud目前还没有准备好，后端技术栈目前只支持eggjs。我们会将springcloud的选项先去掉，待开发完成后再展示
