### ISSUE TITLE
✨ [Feature]: 关于TinyPro增加布局设置的建议

### ISSUE THREAD

**Issue by taoweidong** [opentiny/tiny-cli#74]
###  What does the proposed API look like
TinyPro中后台最佳实践增加一键式切换布局功能。

### What does the proposed API look like

TinyPro中后台最佳实践增加一键式切换布局功能

可以参考：https://docs.soybean.pro/guide/     项目支持布局切换功能

布局切换很于用，建议增加

![image](https://github.com/opentiny/tiny-cli/assets/23622072/84de6793-9b73-438d-a03c-aff1580537c2)

**Comment by wjiangwang** [comment]
非常感谢您的反馈。我们会对此进行设计开发排期

**Comment by hello-yezi** [comment]
你好，我们已支持简易的布局，可查看官网介绍~
https://opentiny.design/vue-pro/docs/layout
https://opentiny.design/ng-pro/docs/layout

请问您是想支持菜单布局吗？

**Comment by taoweidong** [comment]
不是，这个并不支持vue版本，同时，我所期望的是支持布局可以切换，而https://opentiny.design/ng-pro/docs/layout 不是我所期望的

可以参考我所给出的开源项目的示例：https://docs.soybean.pro/guide/ ，提供给用户更简单的操作，谢谢！

**Comment by falcon-jin** [comment]
有计划支持吗

**Comment by falcon-jin** [comment]
希望出这种多布局的方案 https://lyt-top.gitee.io/vue-next-admin-preview/#/login

**Comment by fengyon** [comment]
感谢您提出的建议，此建议非常有用，可以极大地丰富开发场景
但是由于排期原因，短期内没有开发此功能的计划

您可以参考[tinyvue tab组件的文档](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs)自行开发此功能，也欢迎提交PR贡献

最后，我们将暂时关闭此issue，将来有计划时再重开此issue。
如有需求，您也可以重开此issue，我们将重新讨论此功能的计划。
