### ISSUE TITLE
tiny init pro  angular 报如下错误，应该怎么解决。

### ISSUE THREAD

**Issue by scsunchen** [opentiny/tiny-cli#75]
2023-07-16 23:19:38 [tiny-toolkit-pro]: 正在安装客户端 npm 依赖，安装过程需要几十秒，请耐心等待... 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/architect@0.1402.12.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/scsunchen/.npm/_logs/2023-07-16T15_19_38_254Z-debug-0.log
2023-07-16 23:19:45 [tiny-toolkit-pro]: 客户端 npm 依赖安装成功 

--------------------初始化成功,请按下面提示进行操作--------------------

$ cd tiny-pro && tiny start         # 可一键开启项目开发环境
$ tiny help          # 可查看当前套件的详细帮助

**Comment by aliceDxr** [comment]
请问使用的node版本是多少 ~  建议使用v16试试~

**Comment by ziyouchutuwenwu** [comment]
我的issue被close了，我在这里跟吧，16的话，无论是16.0.0还是16.2.1, 都不行，我的系统是linux,看报错stack, 解析器似乎认为是mac,
![image](https://github.com/opentiny/tiny-cli/assets/7458713/d997b08d-639f-4aaf-8bd5-58108a6531af)

**Comment by aliceDxr** [comment]
后续如果还有问题 请再联系我们 ~
