### ISSUE TITLE
tiny init pro 版本中drawer无法使用，没有样式，版本3.6.8

### ISSUE THREAD

**Issue by dlli** [opentiny/tiny-cli#77]
### Version

3.6.8

### node-version

16.18.0

### Link to minimal reproduction

`<template>
  <div>
    <tiny-button @click="fn" type="primary"> 抽屉组件 </tiny-button>
    <tiny-drawer title="标题" :visible="visible" @update:visible="visible = $event">
      <div>内容区域</div>
    </tiny-drawer>
  </div>
</template>

<script>
import { Drawer, Button } from '@opentiny/vue'

export default {
  components: {
    TinyDrawer: Drawer,
    TinyButton: Button
  },
  data() {
    return {
      visible: false
    }
  },
  methods: {
    fn() {
      this.visible = true
    }
  }
}
</script>`

### Step to reproduce

日志没有报错，官方文档中drawer 中附加的css类是“tiny-drawer__main is-right drag-effects”
而我引入drawer后，附加的类是“fixed w-full max-w-full flex flex-col bg-white z-50 shadow-sm border-color-border-separator transition-all ease-linear duration-200 h-full right-0 top-0 border-l-0.5 translate-x-0 drawer-main”

### What is expected

没有样式

### What is actually happening

页面错乱

**Comment by aliceDxr** [comment]
![image](https://github.com/opentiny/tiny-cli/assets/33685369/80b19d72-123e-4fec-8c4e-e932aca51256)
测试正常 检查一下template中组件名是否正确吧 ~

**Comment by dlli** [comment]
![图片](https://github.com/opentiny/tiny-cli/assets/8346779/1173c4b9-f9b7-449c-b05d-d5ed6675f7d5)
![图片](https://github.com/opentiny/tiny-cli/assets/8346779/ad2954c7-bcc2-4f2d-91af-2d22889458e7)

**Comment by aliceDxr** [comment]
在@opentiny/vue @3.8.3复现了这个问题
建议删除node_modules/https://github.com/opentiny 执行npm i 可以解决这个问题
