### ISSUE TITLE
🐛 [Bug]: 列表查询按钮样式错乱

### ISSUE THREAD

**Issue by java668-real1** [opentiny/tiny-cli#79]
### Version

最新的

### node-version

最新的

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-cli/assets/99872936/2513606c-fc25-45ac-8b62-5e26e21c64dc)
列表查询按钮样式错乱，链接：https://opentiny.design/vue-pro/pages/list/table，

### Step to reproduce

电脑分辨率 1920 * 1080
![image](https://github.com/opentiny/tiny-cli/assets/99872936/03f83500-9696-4c17-aee2-d2af6a78812c)

### What is expected

列表查询按钮样式错乱修复

### What is actually happening

列表查询按钮样式错乱

### Any additional comments (optional)

列表查询按钮样式错乱

**Comment by aliceDxr** [comment]
感谢建议 这个问题在@opentiny/tiny-toolkit-pro@1.0.11 已经修复  
如果是已有项目 可以给btn容器添加"display:flex"属性
