### ISSUE TITLE
✨ [Feature]: 希望菜单能点击收缩和展开

### ISSUE THREAD

**Issue by java668-real1** [opentiny/tiny-cli#80]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-cli/assets/99872936/c7624a94-a79d-405c-a484-d08cd24132fd)
希望菜单能点击收缩和展开

### What does the proposed API look like

像其他框架一样，希望菜单能点击收缩和展开，

**Comment by aliceDxr** [comment]
在src/components/menu/index.vue   给tiny-tree-menu组件加上accordion属性即可实现手风琴效果  
可以参考文档：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tree-menu#accordion
