### ISSUE TITLE
🐛 [Bug]: TinyCLI无法运行

### ISSUE THREAD

**Issue by h25302** [opentiny/tiny-cli#88]
### Version

无法运行查看

### node-version

v20.5.1

### Step to reproduce

在docker中运行 npm install @opentiny/cli npminstall@3 -g
后提示安装成功
然后尝试运行 tiny -v
结果出现：
```
You are not allowed to run this app with root permissions.
If running without sudo doesn't work, you can either fix your permission problems or change where npm stores global packages by putting ~/npm/bin in your PATH and running:
npm config set prefix ~/npm

See: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
```

### What is expected

tiny v1.x.x

**Comment by fengyon** [comment]
从报错信息上看是 操作系统权限的问题，有两个修复建议：
1、按npm文档指导修改npm的安装位置
https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md
2、在命令前加上sudo
``` shell
sudo npm install @opentiny/cli -g
```

**Comment by h25302** [comment]
非常感谢 @fengyon 的回复

由于这是直接在 全新安装的node官方docker镜像 里面来运行，所以命令前面加不上sudo

在一切都按照默认的情况下，也就是在 全新安装的node官方docker镜像 中，不做任何附加的操作
奇怪的是：我安装过不少组件以及各种cli，都没有出现过类似的权限问题

**Comment by h25302** [comment]
刚刚我尝试使用yarn进行安装：
`yarn global add @opentiny/cli`

提示安装成功：
```
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@opentiny/cli@1.1.0" with binaries:
      - tiny
Done in 56.85s.
```

然后尝试运行 tiny -v，结果又出现另外的错误：
```
root@xxxxx:/xxx# tiny -v
/usr/bin/env: 'node\r': No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

**Comment by fengyon** [comment]
感谢您的反馈，经过团队讨论，目前TinyCli不支持 linux运行，短期内暂时没有支持 linux的计划

如果您非常期望TinyCli支持linux，可以重开此issue重新进行讨论，也欢迎您提交PR
