### ISSUE TITLE
✨ [Feature]: 建议后台管理增加tab切换页面的界面风格样式

### ISSUE THREAD

**Issue by joyoes** [opentiny/tiny-cli#89]
### What problem does this feature solve

现在很多的VUE3后台都支持TAB切换页面的界面风格，建议你们也增加这种界面样式风格哈

### What does the proposed API look like

现在很多的VUE3后台都支持TAB切换页面的界面风格，建议你们也增加这种界面样式风格哈

**Comment by fengyon** [comment]
tinyvue tab组件有不同的风格，支持左侧、顶部显示tab，您可以参考下，看下是否符合您的要求

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs

**Comment by fengyon** [comment]
感谢您提出的建议，此建议非常有用，可以极大地丰富开发场景
但是由于排期原因，短期内没有开发此功能的计划

您可以参考[tinyvue tab组件的文档](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs)自行开发此功能，也欢迎提交PR贡献

最后，我们将暂时关闭此issue，将来有计划时再重开此issue。
如有需求，您也可以重开此issue，我们将重新讨论此功能的计划
