### ISSUE TITLE
Pro套件初始化后启动报错🐛 [Bug]: 

### ISSUE THREAD

**Issue by minyongbing** [opentiny/tiny-cli#92]
### Version

v1.1.0

### node-version

v18.17.1

### Step to reproduce

按照Pro套件文档操作，不选择数据库，不选择使用后台创建一个工程，最后调用tiny start 启动后报错。

![1693973411087](https://github.com/opentiny/tiny-cli/assets/28675839/6bacc9fc-2bf3-4bf0-ba6f-e342d6d86c91)

**Comment by fengyon** [comment]
感谢您的反馈，这是 vue-i18n 升级到 9.3.0 的问题，后续我们会优化这个问题
修复方案：
1、找到项目的 `vite.config.base.js`文件（pro套件在 `config/vite.config.base.ts` 文件中）
2、添加或者修改以前存在 的 `vue-i18n`的别名设置，指向 `vue-i18n/dist/vue-i18n.esm-bundler.js`
代码示例
``` javascript
export default {
  resolve: {
    alias: [
      {
        find: 'vue-i18n',
        // 修改前 replacement: 'vue-i18n/dist/vue-i18n.cjs.js', // Resolve the i18n warning issue
        replacement: 'vue-i18n/dist/vue-i18n.esm-bundler.js', // Resolve the i18n warning issue
      },
    ],
  },
};
```
详见issue：https://github.com/intlify/vue-i18n-next/issues/1521

**Comment by LinLiang66** [comment]
很棒 已解决  涉及两个文件 都需要修改 
config/vite.config.preview.base.ts
config/vite.config.base.ts 


修改内容：
// 修改前
        // replacement: 'vue-i18n/dist/vue-i18n.cjs.js', // Resolve the i18n warning issue
        // 修改后
        replacement: 'vue-i18n/dist/vue-i18n.esm-bundler.js', // Resolve the i18n warning issue

修改后重新启动项目 即可正常运行

**Comment by fengyon** [comment]
# 修复方案总结：
## 1、修改vue-i18n的替代文件，刚建好的模板中涉及两个文件
config/vite.config.preview.base.ts
config/vite.config.base.ts
...（其他涉及`vue-i18n`的vite配置文件）

``` javascript
export default {
  resolve: {
    alias: [
      {
        find: 'vue-i18n',
        // 修改前 replacement: 'vue-i18n/dist/vue-i18n.cjs.js', // Resolve the i18n warning issue
        replacement: 'vue-i18n/dist/vue-i18n.esm-bundler.js', // Resolve the i18n warning issue
      },
    ],
  },
};
```
## 2、升级`package.json`中`vue-i18`为最新版本
``` bash
npm view vue-i18n
```

package.json文件中：
"vue-i18n": "^9.30.0" （请替换为您使用时的最新版本）
